spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tztestdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
