spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tztestdb
    username: postgres
    password: postgres
logging:
  level:
    root: INFO
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
